name: ocr_engine_tesseract
description:
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: any
  http: any
  uni_ocr_client:
    git:
      path: packages/uni_ocr_client
      ref: master
      url: https://github.com/jiangxiaoqiang/uni_ocr.git


dev_dependencies:
  test: ^1.0.0
