name: uni_ocr
description:
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ocr_engine_tesseract:
    git:
      path: packages/ocr_engine_tesseract
      ref: master
      url: https://github.com/biyidev/uni_ocr.git
  ocr_engine_youdao:
    git:
      path: packages/ocr_engine_youdao
      ref: master
      url: https://github.com/biyidev/uni_ocr.git
  uni_ocr_client: ^0.0.1

dev_dependencies:
  test: ^1.0.0
